<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use Illuminate\Support\Facades\Log;

class CountriesSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        Country::create(['id' => '113', 'name' => 'Россия']);
        Country::create(['id' => '2112', 'name' => 'Абхазия']);
        Country::create(['id' => '5', 'name' => 'Украина']);
        Country::create(['id' => '6', 'name' => 'Австралия']);
        Country::create(['id' => '40', 'name' => 'Казахстан']);
        Country::create(['id' => '7', 'name' => 'Австрия']);
        Country::create(['id' => '9', 'name' => 'Азербайджан']);
        Country::create(['id' => '2357', 'name' => 'Албания']);
        Country::create(['id' => '16', 'name' => 'Беларусь']);
        Country::create(['id' => '2368', 'name' => 'Алжир']);
        Country::create(['id' => '28', 'name' => 'Грузия']);
        Country::create(['id' => '2376', 'name' => 'Ангола']);
        Country::create(['id' => '2354', 'name' => 'Андорра']);
        Country::create(['id' => '48', 'name' => 'Кыргызстан']);
        Country::create(['id' => '235', 'name' => 'Аргентина']);
        Country::create(['id' => '97', 'name' => 'Узбекистан']);
        Country::create(['id' => '13', 'name' => 'Армения']);
        Country::create(['id' => '2110', 'name' => 'Афганистан']);
        Country::create(['id' => '6010', 'name' => 'Багамские Острова']);
        Country::create(['id' => '303', 'name' => 'Бангладеш']);
        Country::create(['id' => '6359', 'name' => 'Барбадос']);
        Country::create(['id' => '2361', 'name' => 'Бахрейн']);
        Country::create(['id' => '5047', 'name' => 'Белиз']);
        Country::create(['id' => '18', 'name' => 'Бельгия']);
        Country::create(['id' => '200', 'name' => 'Болгария']);
        Country::create(['id' => '2228', 'name' => 'Боливия']);
        Country::create(['id' => '2358', 'name' => 'Босния и Герцеговина']);
        Country::create(['id' => '243', 'name' => 'Бразилия']);
        Country::create(['id' => '6329', 'name' => 'Бруней Даруссалам']);
        Country::create(['id' => '306', 'name' => 'Буркина Фасо']);
        Country::create(['id' => '21', 'name' => 'Великобритания']);
        Country::create(['id' => '114', 'name' => 'Венгрия']);
        Country::create(['id' => '2371', 'name' => 'Венесуэла']);
        Country::create(['id' => '203', 'name' => 'Вьетнам']);
        Country::create(['id' => '2586', 'name' => 'Габон']);
        Country::create(['id' => '202', 'name' => 'Гвинея']);
        Country::create(['id' => '27', 'name' => 'Германия']);
        Country::create(['id' => '2435', 'name' => 'Государство Палестина']);
        Country::create(['id' => '213', 'name' => 'Греция']);
        Country::create(['id' => '30', 'name' => 'Дания']);
        Country::create(['id' => '311', 'name' => 'Демократическая Республика Конго']);
        Country::create(['id' => '6517', 'name' => 'Джибути']);
        Country::create(['id' => '2730', 'name' => 'Доминиканская Республика']);
        Country::create(['id' => '305', 'name' => 'Египет']);
        Country::create(['id' => '6367', 'name' => 'Замбия']);
        Country::create(['id' => '33', 'name' => 'Израиль']);
        Country::create(['id' => '209', 'name' => 'Индия']);
        Country::create(['id' => '2108', 'name' => 'Индонезия']);
        Country::create(['id' => '2365', 'name' => 'Иордания']);
        Country::create(['id' => '2232', 'name' => 'Ирак']);
        Country::create(['id' => '2227', 'name' => 'Иран']);
        Country::create(['id' => '36', 'name' => 'Ирландия']);
        Country::create(['id' => '302', 'name' => 'Исландия']);
        Country::create(['id' => '37', 'name' => 'Испания']);
        Country::create(['id' => '38', 'name' => 'Италия']);
        Country::create(['id' => '2109', 'name' => 'Йемен']);
        Country::create(['id' => '245', 'name' => 'Камбоджа']);
        Country::create(['id' => '45', 'name' => 'Канада']);
        Country::create(['id' => '210', 'name' => 'Катар']);
        Country::create(['id' => '236', 'name' => 'Кипр']);
        Country::create(['id' => '50', 'name' => 'Китай']);
        Country::create(['id' => '2113', 'name' => 'Колумбия']);
        Country::create(['id' => '2380', 'name' => 'Кооперативная Республика Гайана']);
        Country::create(['id' => '2362', 'name' => 'Королевство Саудовская Аравия']);
        Country::create(['id' => '2363', 'name' => 'Кувейт']);
        Country::create(['id' => '6323', 'name' => 'Лаос']);
        Country::create(['id' => '57', 'name' => 'Латвия']);
        Country::create(['id' => '2111', 'name' => 'Ливан']);
        Country::create(['id' => '6868', 'name' => 'Другое']);
        Country::create(['id' => '2106', 'name' => 'Ливия']);
        Country::create(['id' => '59', 'name' => 'Литва']);
        Country::create(['id' => '2355', 'name' => 'Лихтенштейн']);
        Country::create(['id' => '206', 'name' => 'Люксембург']);
        Country::create(['id' => '2359', 'name' => 'Македония']);
        Country::create(['id' => '238', 'name' => 'Малайзия']);
        Country::create(['id' => '6518', 'name' => 'Мали']);
        Country::create(['id' => '2798', 'name' => 'Мальдивская Республика']);
        Country::create(['id' => '2353', 'name' => 'Мальта']);
        Country::create(['id' => '2372', 'name' => 'Марокко']);
        Country::create(['id' => '2229', 'name' => 'Мексика']);
        Country::create(['id' => '62', 'name' => 'Молдавия']);
        Country::create(['id' => '2356', 'name' => 'Монако']);
        Country::create(['id' => '2231', 'name' => 'Монголия']);
        Country::create(['id' => '2487', 'name' => 'Мьянма']);
        Country::create(['id' => '2375', 'name' => 'Намибия']);
        Country::create(['id' => '6326', 'name' => 'Непал']);
        Country::create(['id' => '240', 'name' => 'Нигерия']);
        Country::create(['id' => '65', 'name' => 'Нидерланды']);
        Country::create(['id' => '204', 'name' => 'Новая Зеландия']);
        Country::create(['id' => '207', 'name' => 'Норвегия']);
        Country::create(['id' => '208', 'name' => 'ОАЭ']);
        Country::create(['id' => '6058', 'name' => 'Объединенная Республика Танзания']);
        Country::create(['id' => '2364', 'name' => 'Оман']);
        Country::create(['id' => '6521', 'name' => 'Острова Кайман']);
        Country::create(['id' => '316', 'name' => 'Пакистан']);
        Country::create(['id' => '2587', 'name' => 'Панама']);
        Country::create(['id' => '6327', 'name' => 'Парагвай']);
        Country::create(['id' => '2395', 'name' => 'Перу']);
        Country::create(['id' => '74', 'name' => 'Польша']);
        Country::create(['id' => '241', 'name' => 'Португалия']);
        Country::create(['id' => '2752', 'name' => 'Республика Бенин']);
        Country::create(['id' => '6377', 'name' => 'Республика Гаити']);
        Country::create(['id' => '2491', 'name' => 'Республика Гана']);
        Country::create(['id' => '5131', 'name' => 'Республика Гватемала']);
        Country::create(['id' => '2504', 'name' => 'Республика Зимбабве']);
        Country::create(['id' => '2669', 'name' => 'Республика Камерун']);
        Country::create(['id' => '2453', 'name' => 'Республика Кения']);
        Country::create(['id' => '312', 'name' => 'Республика Конго']);
        Country::create(['id' => '2636', 'name' => 'Республика Коста-Рика']);
        Country::create(['id' => '2454', 'name' => 'Республика Кот-д’Ивуар']);
        Country::create(['id' => '2635', 'name' => 'Республика Куба']);
        Country::create(['id' => '2398', 'name' => 'Республика Либерия']);
        Country::create(['id' => '2370', 'name' => 'Республика Маврикий']);
        Country::create(['id' => '2488', 'name' => 'Республика Мадагаскар']);
        Country::create(['id' => '6337', 'name' => 'Республика Малави']);
        Country::create(['id' => '2378', 'name' => 'Республика Нигер']);
        Country::create(['id' => '3666', 'name' => 'Республика Никарагуа']);
        Country::create(['id' => '2446', 'name' => 'Республика Северный Судан']);
        Country::create(['id' => '2367', 'name' => 'Республика Сейшельские острова']);
        Country::create(['id' => '2374', 'name' => 'Республика Сенегал']);
        Country::create(['id' => '6504', 'name' => 'Республика Сьерра-Леоне']);
        Country::create(['id' => '6350', 'name' => 'Республика Чад']);
        Country::create(['id' => '6356', 'name' => 'Республика Эль-Сальвадор']);
        Country::create(['id' => '2369', 'name' => 'Реюньон']);
        Country::create(['id' => '234', 'name' => 'Румыния']);
        Country::create(['id' => '5048', 'name' => 'Сент-Винсент и Гренадины']);
        Country::create(['id' => '146', 'name' => 'Сербия']);
        Country::create(['id' => '233', 'name' => 'Сингапур']);
        Country::create(['id' => '317', 'name' => 'Сирия']);
        Country::create(['id' => '318', 'name' => 'Словакия']);
        Country::create(['id' => '2105', 'name' => 'Словения']);
        Country::create(['id' => '85', 'name' => 'США']);
        Country::create(['id' => '86', 'name' => 'Таджикистан']);
        Country::create(['id' => '300', 'name' => 'Таиланд']);
        Country::create(['id' => '148', 'name' => 'Тайвань']);
        Country::create(['id' => '6330', 'name' => 'Тоголезская Республика']);
        Country::create(['id' => '244', 'name' => 'Тунис']);
        Country::create(['id' => '93', 'name' => 'Туркменистан']);
        Country::create(['id' => '94', 'name' => 'Турция']);
        Country::create(['id' => '4635', 'name' => 'Уганда']);
        Country::create(['id' => '2810', 'name' => 'Уругвай']);
        Country::create(['id' => '2360', 'name' => 'Филиппины']);
        Country::create(['id' => '100', 'name' => 'Финляндия']);
        Country::create(['id' => '101', 'name' => 'Франция']);
        Country::create(['id' => '2103', 'name' => 'Хорватия']);
        Country::create(['id' => '6448', 'name' => 'Центральноафриканская Республика']);
        Country::create(['id' => '5046', 'name' => 'Черногория']);
        Country::create(['id' => '199', 'name' => 'Чехия']);
        Country::create(['id' => '2396', 'name' => 'Чили']);
        Country::create(['id' => '108', 'name' => 'Швейцария']);
        Country::create(['id' => '149', 'name' => 'Швеция']);
        Country::create(['id' => '239', 'name' => 'Шотландия']);
        Country::create(['id' => '2511', 'name' => 'Шри-Ланка']);
        Country::create(['id' => '242', 'name' => 'Эквадор']);
        Country::create(['id' => '6328', 'name' => 'Эритрея']);
        Country::create(['id' => '109', 'name' => 'Эстония']);
        Country::create(['id' => '2520', 'name' => 'Эфиопия']);
        Country::create(['id' => '211', 'name' => 'ЮАР']);
        Country::create(['id' => '110', 'name' => 'Южная Корея']);
        Country::create(['id' => '2524', 'name' => 'Южная Осетия']);
        Country::create(['id' => '2440', 'name' => 'Ямайка']);
        Country::create(['id' => '111', 'name' => 'Япония']);
    }
}
