<?php

namespace Database\Seeders;

use App\Models\Languages;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seeders = [
            ["lang_id" => "abk",
                "name"=>"Абхазский"],
            ["lang_id" => "abq",
                "name"=>"Абазинский"],
            ["lang_id" => "afr",
                "name"=>"Африкаанс"],
            ["lang_id" => "amh",
                "name"=>"Амхарский"],
            ["lang_id" => "ara",
                "name"=>"Арабский"],
            ["lang_id" => "ava",
                "name"=>"Аварский"],
            ["lang_id" => "aze",
                "name"=>"Азербайджанский"],
            ["lang_id" => "bak",
                "name"=>"Башкирский"],
            ["lang_id" => "bel",
                "name"=>"Белорусский"],
            ["lang_id" => "ben",
                "name"=>"Бенгальский"],
            ["lang_id" => "bod",
                "name"=>"Тибетский"],
            ["lang_id" => "bos",
                "name"=>"Боснийский"],
            ["lang_id" => "bua",
                "name"=>"Бурятский"],
            ["lang_id" => "bul",
                "name"=>"Болгарский"],
            ["lang_id" => "cat",
                "name"=>"Каталанский"],
            ["lang_id" => "ces",
                "name"=>"Чешский"],
            ["lang_id" => "che",
                "name"=>"Чеченский"],
            ["lang_id" => "chm",
                "name"=>"Марийский"],
            ["lang_id" => "chv",
                "name"=>"Чувашский"],
            ["lang_id" => "crs",
                "name"=>"Креольский (Сейшельские острова)"],
            ["lang_id" => "dag",
                "name"=>"Дагестанский"],
            ["lang_id" => "dan",
                "name"=>"Датский"],
            ["lang_id" => "dar",
                "name"=>"Даргинский"],
            ["lang_id" => "deu",
                "name"=>"Немецкий"],
            ["lang_id" => "ell",
                "name"=>"Греческий"],
            ["lang_id" => "eng",
                "name"=>"Английский"],
            ["lang_id" => "epo",
                "name"=>"Эсперанто"],
            ["lang_id" => "est",
                "name"=>"Эстонский"],
            ["lang_id" => "eus",
                "name"=>"Баскский"],
            ["lang_id" => "fas",
                "name"=>"Персидский"],
            ["lang_id" => "fin",
                "name"=>"Финский"],
            ["lang_id" => "fra",
                "name"=>"Французский"],
            ["lang_id" => "gle",
                "name"=>"Ирландский"],
            ["lang_id" => "heb",
                "name"=>"Иврит"],
            ["lang_id" => "hin",
                "name"=>"Хинди"],
            ["lang_id" => "hrv",
                "name"=>"Хорватский"],
            ["lang_id" => "hun",
                "name"=>"Венгерский"],
            ["lang_id" => "hye",
                "name"=>"Армянский"],
            ["lang_id" => "ind",
                "name"=>"Индонезийский"],
            ["lang_id" => "inh",
                "name"=>"Ингушский"],
            ["lang_id" => "isl",
                "name"=>"Исландский"],
            ["lang_id" => "ita",
                "name"=>"Итальянский"],
            ["lang_id" => "jpn",
                "name"=>"Японский"],
            ["lang_id" => "kas",
                "name"=>"Кашмирский"],
            ["lang_id" => "kat",
                "name"=>"Грузинский"],
            ["lang_id" => "kaz",
                "name"=>"Казахский"],
            ["lang_id" => "kbd",
                "name"=>"Кабардино-черкесский"],
            ["lang_id" => "khm",
                "name"=>"Кхмерский (Камбоджийский)"],
            ["lang_id" => "kir",
                "name"=>"Кыргызский"],
            ["lang_id" => "kom",
                "name"=>"Коми"],
            ["lang_id" => "kor",
                "name"=>"Корейский"],
            ["lang_id" => "krc",
                "name"=>"Карачаево-балкарский"],
            ["lang_id" => "krl",
                "name"=>"Карельский"],
            ["lang_id" => "kum",
                "name"=>"Кумыкский"],
            ["lang_id" => "kur",
                "name"=>"Курдский"],
            ["lang_id" => "lao",
                "name"=>"Лаосский"],
            ["lang_id" => "lat",
                "name"=>"Латинский"],
            ["lang_id" => "lav",
                "name"=>"Латышский"],
            ["lang_id" => "lbe",
                "name"=>"Лакский"],
            ["lang_id" => "lez",
                "name"=>"Лезгинский"],
            ["lang_id" => "lit",
                "name"=>"Литовский"],
            ["lang_id" => "mke",
                "name"=>"Македонский"],
            ["lang_id" => "mns",
                "name"=>"Мансийский"],
            ["lang_id" => "mon",
                "name"=>"Монгольский"],
            ["lang_id" => "mya",
                "name"=>"Бирманский"],
            ["lang_id" => "nep",
                "name"=>"Непальский"],
            ["lang_id" => "nld",
                "name"=>"Голландский"],
            ["lang_id" => "nog",
                "name"=>"Ногайский"],
            ["lang_id" => "nor",
                "name"=>"Норвежский"],
            ["lang_id" => "oss",
                "name"=>"Осетинский"],
            ["lang_id" => "pan",
                "name"=>"Панджаби"],
            ["lang_id" => "pol",
                "name"=>"Польский"],
            ["lang_id" => "por",
                "name"=>"Португальский"],
            ["lang_id" => "pus",
                "name"=>"Пушту"],
            ["lang_id" => "ron",
                "name"=>"Румынский"],
            ["lang_id" => "rus",
                "name"=>"Русский"],
            ["lang_id" => "sah",
                "name"=>"Якутский"],
            ["lang_id" => "san",
                "name"=>"Санскрит"],
            ["lang_id" => "slk",
                "name"=>"Словацкий"],
            ["lang_id" => "slv",
                "name"=>"Словенский"],
            ["lang_id" => "som",
                "name"=>"Сомалийский"],
            ["lang_id" => "spa",
                "name"=>"Испанский"],
            ["lang_id" => "sqi",
                "name"=>"Албанский"],
            ["lang_id" => "srp",
                "name"=>"Сербский"],
            ["lang_id" => "swa",
                "name"=>"Суахили"],
            ["lang_id" => "swe",
                "name"=>"Шведский"],
            ["lang_id" => "tam",
                "name"=>"Тамильский"],
            ["lang_id" => "tat",
                "name"=>"Татарский"],
            ["lang_id" => "tgk",
                "name"=>"Таджикский"],
            ["lang_id" => "tgl",
                "name"=>"Тагальский"],
            ["lang_id" => "tha",
                "name"=>"Тайский"],
            ["lang_id" => "tly",
                "name"=>"Талышский"],
            ["lang_id" => "tuk",
                "name"=>"Туркменский"],
            ["lang_id" => "tur",
                "name"=>"Турецкий"],
            ["lang_id" => "tyv",
                "name"=>"Тувинский"],
            ["lang_id" => "udm",
                "name"=>"Удмуртский"],
            ["lang_id" => "uig",
                "name"=>"Уйгурский"],
            ["lang_id" => "ukr",
                "name"=>"Украинский"],
            ["lang_id" => "urd",
                "name"=>"Урду"],
            ["lang_id" => "uzb",
                "name"=>"Узбекский"],
            ["lang_id" => "vie", "name"=>"Вьетнамский"],
            ["lang_id" => "vls", "name"=>"Фламандский"],
            ["lang_id" => "zho", "name"=>"Китайский"],
            ["lang_id" => "zlm", "name"=>"Малазийский"]
        ];

        foreach ($seeders as $item) {
            Languages::create($item);
        }
    }
}
